title: Mr.Liu
description: Personal website
sitename: Mr.liu
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
